export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

export const GET_CHATROOMS = "GET_CHATROOMS";
export const CREATE_CHATROOM = "CREATE_CHATROOM";
export const DELETE_CHATROOM = "DELETE_CHATROOM";
export const SET_LOADING_STATE = "SET_LOADING_STATE";
